### ISSUE TITLE
Feature request : Zip on the fly

### ISSUE THREAD

**Issue by BloodMan29** [mccxiv/torrent-web#1]
Hi !!
Firstly, awesome thing you got there :D Keep continue :)
But could you add like a big button over the file list to download in a zip file all the files contain in the actual directory that would be great ! 

Thanks !

**Comment by mccxiv** [comment]
Hey! That's a good idea, I'll see what I can do next week

**Comment by mccxiv** [comment]
We did it! If you have a Heroku build you can set it to automatically update when I push.
New zip download button is next to the torrent name.

![](http://puu.sh/ngDNc/3e214ff56b.png)
