### ISSUE TITLE
Heroku is Over for torrent-web.

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [mccxiv/torrent-web#15]
Any other platform to deply?

**Comment by mccxiv** [comment]
Interesting, is it explicitly banned?

**Comment by ParveenBhadooOfficial** [comment]
Yes, deploy the app. It will be suspended in a few minutes. Even if you do not use it. Same happened to cloud-torrent last year.

**Comment by Eastkap** [comment]
I actually deployed with no issues today

**Comment by ParveenBhadooOfficial** [comment]
Yeah, looks like it started working.

**Comment by askfriends** [comment]
is it working?

can we download to our td?

**Comment by ParveenBhadooOfficial** [comment]
@askfriends Dead for Heroku.
