### ISSUE TITLE
Impossible to build for Heroku.

### ISSUE THREAD

**Issue by BloodMan29** [mccxiv/torrent-web#2]
Hi,
Thanks A LOT for your update, that's gonna help me so hard ! :)
But when I try to build the app it gives me an error [here it is](http://pastebin.com/JDgwNLyJ).

Thanks again !

**Comment by mccxiv** [comment]
Oops.

Should be fixed, thanks for reporting.

**Comment by BloodMan29** [comment]
Thanks man !!
And just to be clear I didn't want my first sentence looks ironic :D and i'm really glad you make it !
