### ISSUE TITLE
get error on heroko while deploying

### ISSUE THREAD

**Issue by buziyborni** [mccxiv/torrent-web#4]
am getting error while deploying how do i fix it

**Comment by mccxiv** [comment]
Thanks for the report, should be fixed :+1:

**Comment by buziyborni** [comment]
You welcome please can you add more features

**Comment by BloodMan29** [comment]
Like ? You have ideas ? :)

**Comment by buziyborni** [comment]
Yeah features like download to a cloud server like mega, google drive, etc and should have where you can delete a torrent that have been added also the web ul should be re design i can help with the design but i don't no how to use angular
