### ISSUE TITLE
No torrent download progress

### ISSUE THREAD

**Issue by shashi007** [mccxiv/torrent-web#6]
Why there's no torrent download progress, how would i know if the torrent is ready for download?

**Comment by mccxiv** [comment]
The progress bar is provided by your browser. You start the download immediately - no need to wait for it to be finished on the server. 

Are you having an issue with it?

**Comment by shashi007** [comment]
Ah, I get it now. Actually i was trying to get the files on other server, it takes a lot of time for bigger files to get on another server. Anyways it's really cool.
Also would like to tell you the direct torrent link doesn't work(I get this message "Invalid Torrent") only magnet link works for me.
